### ISSUE TITLE
New Beacon 4 docker images

### ISSUE THREAD

**Issue by markwilkinson** [ejp-rd-vp/EJP-FiaB-Updates#33]
Pablo has completed the docker images for Beacon version 4, and they are now the default in the FiaB installer.

Usage instructions here:  https://github.com/CARE-SM/beaconAPI4CARESM

IMAGE:  pabloalarconm/beacon-api4care-sm:4.0.0

**Comment by markwilkinson** [comment]
Small bug fix, and I have asked Pablo to make it possible to add a path fragment to the API, in case you need to distinguish Beacon version 4 and Beacon version 2 via a proxy.

pabloalarconm/beacon-api4care-sm:4.0.1

      - PROXY_PATH=proxy

If you were serving Beacon4 /individuals and Beacon2 /individuals on the same server, you can distinguish them by adding a proxy-path such as "beacon4"

- PROXY_PATH=beacon4

means the beacon4 /individuals endpoint will be served as if it were at /beacon4/individuals

so you can proxy pass based on the url regexp match /beacon4/

Hopefully that's clear enough??


```
image: pabloalarconm/beacon-api4care-sm:4.0.1
    ports:
      - "8000:8000"
    environment:
      - TRIPLESTORE_URL=https://
      - TRIPLESTORE_USERNAME=a
      - TRIPLESTORE_PASSWORD=b
      - URL_SERVER=http://0.0.0.0:8000/
      - PROXY_PATH=proxy

      - FILTER_SEX=True
      - FILTER_DISEASE=True
      - FILTER_SYMPTOM=True
      - FILTER_GENE_VARIANT=True
      - FILTER_BIRTHYEAR=True
      - FILTER_AGE_SYMPTOM_ONSET=True
      - FILTER_AGE_DIAGNOSIS=True
   ```
